# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1364e1fcdb6093a89251f2a4ccc0737c743856c1cc358b75a842643712706334056ae0590ed741e69b13bdc0c8a02cdce0dff1c4976a635f940e5101bf3710d4

test:
  secret_key_base: 8bb8d2f54f6ef680b0261252244ff66c2e272d83649b0ef5c8ea4411573cba25d36b27b340c67e50e1ce31ede7eb0454a7dc9c11491fc6adb1fbaef8546a6bcc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
